import { useState, useMemo } from 'react'
import { ArrowLeft, LayoutDashboard, Search, Clock, Share2, FileText, Download, GitCompare, AlertTriangle } from 'lucide-react'
import Leaderboard from './Leaderboard'
import RadarChart from './RadarChart'
import PromiseTracker from './PromiseTracker'
import WordCloud from './WordCloud'
import TimelineChart from './TimelineChart'
import ActivityHeatmap from './ActivityHeatmap'
import NetworkGraph from './NetworkGraph'
import ComparePanel from './ComparePanel'
import { deriveRole } from './MemberCard'
import jsPDF from 'jspdf'

const TABS = [
  { id: 'overview',  label: 'Overview',  icon: LayoutDashboard },
  { id: 'deepdive',  label: 'Deep Dive', icon: Search },
  { id: 'timeline',  label: 'Timeline',  icon: Clock },
  { id: 'compare',   label: 'Compare',   icon: GitCompare },
  { id: 'network',   label: 'Network',   icon: Share2 },
  { id: 'report',    label: 'Report',    icon: FileText },
]

function StatCard({ label, value, sub }) {
  return (
    <div className="glass p-4 rounded-xl">
      <p className="text-gray-400 text-xs mb-1">{label}</p>
      <p className="text-2xl font-bold font-heading gradient-text">{value}</p>
      {sub && <p className="text-xs text-gray-500 mt-1">{sub}</p>}
    </div>
  )
}

export default function Dashboard({ parsedData, analysisData, onReset }) {
  const [activeTab, setActiveTab] = useState('overview')
  const [selectedMember, setSelectedMember] = useState(null)

  const members = analysisData?.analysis?.members || []
  const report = analysisData?.report || ''

  const topMember = [...members].sort((a, b) => (b.overall_score ?? 0) - (a.overall_score ?? 0))[0]
  const currentMember = selectedMember || members[0] || null

  const totalMessages = parsedData?.length || 0
  const uniqueMembers = members.length
  const avgScore = members.length
    ? (members.reduce((s, m) => s + (m.overall_score ?? 0), 0) / members.length).toFixed(1)
    : 0

  // --- Build per-member message count map from parsedData ---
  const messageCounts = useMemo(() => {
    const counts = {}
    parsedData?.forEach(msg => {
      counts[msg.name] = (counts[msg.name] || 0) + 1
    })
    return counts
  }, [parsedData])

  // --- Ghost member detection ---
  // Ghost = role derived as "Ghost" (message_frequency score ≤ 3)
  const ghostMembers = useMemo(
    () => members.filter(m => deriveRole(m).label === 'Ghost'),
    [members]
  )

  // --- Export PDF ---
  const handleExportPDF = () => {
    const doc = new jsPDF()
    doc.setFontSize(20)
    doc.setFont('helvetica', 'bold')
    doc.text('TeamLens — Faculty Evaluation Report', 20, 20)

    doc.setFontSize(11)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(60, 60, 60)

    const lines = doc.splitTextToSize(report, 170)
    doc.text(lines, 20, 35)

    doc.setFontSize(9)
    doc.setTextColor(150)
    doc.text('Generated by TeamLens · Data is not stored or shared', 20, 285)

    doc.save('TeamLens_Report.pdf')
  }

  // --- Export JSON ---
  const handleExportJSON = () => {
    const payload = {
      generated_at: new Date().toISOString(),
      parsed_messages: parsedData,
      analysis: analysisData,
    }
    const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'TeamLens_analysis.json'
    a.click()
    URL.revokeObjectURL(url)
  }

  if (!members.length) {
    return (
      <div className="min-h-screen bg-bg flex flex-col items-center justify-center text-center px-4">
        <p className="text-2xl font-heading font-bold gradient-text mb-4">No member data found</p>
        <p className="text-gray-400 mb-6">The analysis did not return any member contributions.<br/>This can happen if the AI response was truncated or the chat was too short.</p>
        <button onClick={onReset} className="px-6 py-2 rounded-lg bg-primary text-white font-semibold hover:opacity-90 transition">
          ← Try Again
        </button>
        {report && (
          <div className="mt-8 glass p-6 rounded-xl max-w-2xl text-left">
            <p className="text-sm text-gray-300 font-heading mb-2">Raw report returned:</p>
            <p className="text-gray-400 text-sm whitespace-pre-wrap">{report}</p>
          </div>
        )}
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-bg">
      {/* Header */}
      <header className="glass border-b border-border sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 py-3 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <button
              onClick={onReset}
              className="flex items-center gap-1 text-gray-400 hover:text-accent transition-colors text-sm"
            >
              <ArrowLeft className="w-4 h-4" />
              New Analysis
            </button>
            <span className="text-border">|</span>
            <span className="font-heading font-bold gradient-text text-lg">TeamLens</span>
          </div>
          <div className="flex items-center gap-3 text-sm text-gray-400">
            <span>👥 {uniqueMembers} members</span>
            <span>💬 {totalMessages} messages</span>
            <span>⭐ Avg {avgScore}</span>
          </div>
        </div>
      </header>

      {/* Tabs */}
      <div className="max-w-7xl mx-auto px-4 pt-4">
        <div className="flex gap-2 overflow-x-auto pb-2">
          {TABS.map(tab => {
            const Icon = tab.icon
            const active = activeTab === tab.id
            return (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={`flex items-center gap-2 px-4 py-2 rounded-xl font-medium text-sm whitespace-nowrap transition-all duration-200 flex-shrink-0
                  ${active ? 'tab-active' : 'tab-inactive'}`}
              >
                <Icon className="w-4 h-4" />
                {tab.label}
              </button>
            )
          })}
        </div>
      </div>

      {/* Content */}
      <main className="max-w-7xl mx-auto px-4 py-6 space-y-6">

        {/* TAB: OVERVIEW */}
        {activeTab === 'overview' && (
          <div className="animate-fade-in space-y-6">
            {/* Stats row */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <StatCard label="Total Messages" value={totalMessages} sub="after filtering" />
              <StatCard label="Team Members" value={uniqueMembers} />
              <StatCard label="Average Score" value={avgScore} sub="out of 10" />
              <StatCard label="Top Contributor" value={topMember?.name || '—'} sub={`Score: ${topMember?.overall_score?.toFixed(1) || '—'}`} />
            </div>

            {/* Ghost member alert */}
            {ghostMembers.length > 0 && (
              <div className="glass p-4 rounded-2xl border border-yellow-500/30 bg-yellow-500/5 animate-fade-in">
                <div className="flex items-start gap-3">
                  <AlertTriangle className="w-5 h-5 text-yellow-400 flex-shrink-0 mt-0.5" />
                  <div>
                    <p className="text-yellow-400 font-semibold font-heading text-sm mb-1">
                      👻 Participation Risk — {ghostMembers.length} member{ghostMembers.length > 1 ? 's' : ''} flagged
                    </p>
                    <p className="text-gray-400 text-xs mb-2">
                      The following members have very low message frequency and may not be contributing meaningfully:
                    </p>
                    <div className="flex flex-wrap gap-2">
                      {ghostMembers.map(m => (
                        <button
                          key={m.name}
                          onClick={() => { setSelectedMember(m); setActiveTab('deepdive') }}
                          className="px-3 py-1 rounded-full text-xs font-semibold bg-gray-500/20 text-gray-300 border border-gray-500/30 hover:border-yellow-400/50 transition-colors"
                        >
                          {m.name} ({messageCounts[m.name] ?? 0} msgs)
                        </button>
                      ))}
                    </div>
                  </div>
                </div>
              </div>
            )}

            {/* Leaderboard */}
            <Leaderboard
              members={members}
              messageCounts={messageCounts}
              onSelectMember={(m) => { setSelectedMember(m); setActiveTab('deepdive') }}
              selectedMember={selectedMember}
            />
          </div>
        )}

        {/* TAB: DEEP DIVE */}
        {activeTab === 'deepdive' && (
          <div className="animate-fade-in space-y-6">
            {/* Member selector */}
            <div className="flex items-center gap-3">
              <label className="text-sm text-gray-400 font-medium">Viewing:</label>
              <select
                value={currentMember?.name || ''}
                onChange={e => setSelectedMember(members.find(m => m.name === e.target.value))}
                className="bg-surface border border-border text-accent rounded-xl px-4 py-2 text-sm focus:outline-none focus:border-primary"
              >
                {members.map(m => (
                  <option key={m.name} value={m.name}>{m.name}</option>
                ))}
              </select>
            </div>

            {currentMember && (
              <>
                {/* Summary */}
                <div className="glass p-5 rounded-2xl">
                  <div className="flex items-start justify-between gap-4 flex-wrap">
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-3 flex-wrap mb-2">
                        <h2 className="font-heading text-xl font-bold text-accent">{currentMember.name}</h2>
                        {/* Role badge in deep dive */}
                        {(() => {
                          const role = deriveRole(currentMember)
                          return (
                            <span
                              className="px-3 py-1 rounded-full text-xs font-semibold"
                              style={{ color: role.color, background: role.bg, border: `1px solid ${role.border}` }}
                            >
                              {role.label}
                            </span>
                          )
                        })()}
                        <span className="text-xs text-gray-500">
                          💬 {messageCounts[currentMember.name] ?? 0} messages
                        </span>
                      </div>
                      <p className="text-gray-300 text-sm leading-relaxed">{currentMember.summary}</p>
                    </div>
                    <div className={`px-4 py-2 rounded-xl text-2xl font-bold flex-shrink-0 ${
                      (currentMember.overall_score ?? 0) >= 7 ? 'badge-green' :
                      (currentMember.overall_score ?? 0) >= 4 ? 'badge-yellow' : 'badge-red'
                    }`}>
                      {(currentMember.overall_score ?? 0).toFixed(1)}
                    </div>
                  </div>
                </div>

                <div className="grid md:grid-cols-2 gap-4">
                  <RadarChart member={currentMember} />
                  <WordCloud words={currentMember.top_words} />
                </div>

                <PromiseTracker member={currentMember} />

                {/* Avg response time */}
                {currentMember.avg_response_time_hours !== undefined && (
                  <div className="glass p-4 rounded-xl flex items-center gap-4">
                    <Clock className="w-5 h-5 text-primary" />
                    <div>
                      <p className="text-sm text-gray-400">Average Response Time</p>
                      <p className="font-semibold text-accent">{currentMember.avg_response_time_hours.toFixed(1)} hours</p>
                    </div>
                  </div>
                )}
              </>
            )}
          </div>
        )}

        {/* TAB: TIMELINE */}
        {activeTab === 'timeline' && (
          <div className="animate-fade-in space-y-6">
            <TimelineChart parsedData={parsedData} members={members} />
            <ActivityHeatmap parsedData={parsedData} />

            {/* First/last message table */}
            <div className="glass p-5 rounded-2xl">
              <h3 className="font-heading font-semibold text-accent mb-4">Member Activity Range</h3>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b border-border">
                      <th className="text-left py-2 px-3 text-gray-400 font-medium">Member</th>
                      <th className="text-left py-2 px-3 text-gray-400 font-medium">First Message</th>
                      <th className="text-left py-2 px-3 text-gray-400 font-medium">Last Message</th>
                    </tr>
                  </thead>
                  <tbody>
                    {members.map(m => {
                      const msgs = parsedData.filter(p => p.name === m.name)
                      const first = msgs[0]
                      const last = msgs[msgs.length - 1]
                      return (
                        <tr key={m.name} className="border-b border-border/40 hover:bg-surface/50">
                          <td className="py-2 px-3 font-medium text-accent">{m.name}</td>
                          <td className="py-2 px-3 text-gray-400">{first ? new Date(first.timestamp).toLocaleString() : '—'}</td>
                          <td className="py-2 px-3 text-gray-400">{last ? new Date(last.timestamp).toLocaleString() : '—'}</td>
                        </tr>
                      )
                    })}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        )}

        {/* TAB: COMPARE */}
        {activeTab === 'compare' && (
          <ComparePanel members={members} messageCounts={messageCounts} />
        )}

        {/* TAB: NETWORK */}
        {activeTab === 'network' && (
          <div className="animate-fade-in">
            <NetworkGraph parsedData={parsedData} members={members} />
          </div>
        )}

        {/* TAB: REPORT */}
        {activeTab === 'report' && (
          <div className="animate-fade-in space-y-6">
            <div className="flex items-center justify-between flex-wrap gap-3">
              <h2 className="font-heading text-xl font-bold gradient-text">Faculty Evaluation Report</h2>
              <div className="flex items-center gap-3">
                <button
                  onClick={handleExportJSON}
                  className="flex items-center gap-2 px-4 py-2.5 bg-surface hover:bg-border text-accent rounded-xl font-medium text-sm transition-all border border-border hover:border-primary/50 hover:scale-105"
                >
                  <Download className="w-4 h-4" />
                  Export JSON
                </button>
                <button
                  onClick={handleExportPDF}
                  className="flex items-center gap-2 px-5 py-2.5 bg-primary hover:bg-indigo-500 text-white rounded-xl font-medium text-sm transition-all glow-primary hover:scale-105"
                >
                  <Download className="w-4 h-4" />
                  Export PDF
                </button>
              </div>
            </div>

            <div className="glass p-8 rounded-2xl">
              <div className="prose max-w-none">
                {report.split('\n\n').map((para, i) => (
                  <p key={i} className="text-gray-300 leading-relaxed mb-4 text-sm md:text-base">
                    {para}
                  </p>
                ))}
              </div>
            </div>

            {/* Scores summary table */}
            <div className="glass p-5 rounded-2xl">
              <h3 className="font-heading font-semibold text-accent mb-4">Score Summary</h3>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b border-border">
                      <th className="text-left py-2 px-3 text-gray-400">Member</th>
                      <th className="text-left py-2 px-3 text-gray-400">Role</th>
                      <th className="text-center py-2 px-3 text-gray-400">Msgs</th>
                      <th className="text-center py-2 px-3 text-gray-400">Frequency</th>
                      <th className="text-center py-2 px-3 text-gray-400">Initiative</th>
                      <th className="text-center py-2 px-3 text-gray-400">Ownership</th>
                      <th className="text-center py-2 px-3 text-gray-400">Follow-Through</th>
                      <th className="text-center py-2 px-3 text-gray-400">Responsive</th>
                      <th className="text-center py-2 px-3 text-gray-400">Overall</th>
                    </tr>
                  </thead>
                  <tbody>
                    {members.map(m => {
                      const role = deriveRole(m)
                      return (
                        <tr key={m.name} className="border-b border-border/40 hover:bg-surface/50">
                          <td className="py-2 px-3 font-medium text-accent">{m.name}</td>
                          <td className="py-2 px-3">
                            <span
                              className="px-2 py-0.5 rounded-full text-xs font-semibold"
                              style={{ color: role.color, background: role.bg, border: `1px solid ${role.border}` }}
                            >
                              {role.label}
                            </span>
                          </td>
                          <td className="py-2 px-3 text-center text-gray-300">{messageCounts[m.name] ?? 0}</td>
                          <td className="py-2 px-3 text-center text-gray-300">{m.scores?.message_frequency?.toFixed(1)}</td>
                          <td className="py-2 px-3 text-center text-gray-300">{m.scores?.initiative?.toFixed(1)}</td>
                          <td className="py-2 px-3 text-center text-gray-300">{m.scores?.task_ownership?.toFixed(1)}</td>
                          <td className="py-2 px-3 text-center text-gray-300">{m.scores?.follow_through?.toFixed(1)}</td>
                          <td className="py-2 px-3 text-center text-gray-300">{m.scores?.responsiveness?.toFixed(1)}</td>
                          <td className="py-2 px-3 text-center">
                            <span className={`px-2 py-0.5 rounded-full text-xs font-bold ${
                              (m.overall_score ?? 0) >= 7 ? 'badge-green' :
                              (m.overall_score ?? 0) >= 4 ? 'badge-yellow' : 'badge-red'
                            }`}>
                              {(m.overall_score ?? 0).toFixed(1)}
                            </span>
                          </td>
                        </tr>
                      )
                    })}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        )}
      </main>
    </div>
  )
}
